// Independent modules derived from the supplied feature sheets.
export const modules = [
  ["messagetracker", "Message tracker", ["messages", "add message", "remove message", "reset message", "blacklist add", "blacklist remove", "blacklist list", "manager"]],
  ["reminder", "Reminders", ["reminder", "start", "stop", "pause", "resume", "end", "list"]],
  ["timer", "Timers", ["timer", "start", "stop", "pause", "resume", "end", "list"]],
  ["media", "Media channels", ["media", "channel add", "channel remove", "channel reset", "bypass add", "bypass view", "bypass reset", "config"]],
  ["autoresponder", "Auto responder & reactions", ["autoreactor", "autoreactor set", "autoreactor list", "autoreactor mode", "autoreactor allowed", "autoreactor remove", "autoreactor config", "autoresponder", "autoresponder set", "autoresponder list", "autoresponder mode", "autoresponder allowed", "autoresponder remove", "autoresponder config", "autoresponder variables"]],
  ["automod", "Automod", ["antiinvite", "antilink", "antimassmention", "antinsfw", "antispam", "antiswear", "automod", "config", "enable", "disable", "bypass", "logs", "punishment", "limit", "create", "delete", "list", "setup"]],
  ["customise", "Customisation & aliases", ["aliases", "aliases set", "aliases remove", "aliases list", "aliases reset", "customise", "avatar", "banner", "bio", "reset"]],
  ["customrole", "Custom roles", ["customrole", "add", "remove", "config", "reset", "list", "reqrole"]],
  ["guildtag", "Guild tags", ["guildtag", "set", "sync", "reset", "channel", "message", "testmessage", "config"]],
  ["vanityrole", "Vanity roles", ["vanityrole", "set", "reset", "channel", "message", "testmessage", "config"]],
  ["social", "Social notifications", ["kicknotify", "kicknotify add", "kicknotify remove", "kicknotify pingrole", "kicknotify config", "kicknotify reset", "twitch", "twitch add", "twitch remove", "twitch pingrole", "twitch config", "twitch reset", "youtube", "youtube add", "youtube remove", "youtube pingrole", "youtube config", "youtube reset"]],
  ["mod", "Moderation", ["add", "remove", "permit", "immune", "list", "reset", "audit", "ban", "chatban", "chatunban", "hide", "unhide", "kick", "lock", "unlock", "mute", "unmute", "nick", "purge", "rename", "role", "slowmode", "snipe", "warn", "vcban", "vcmute"]],
  ["stickymessage", "Sticky messages", ["stickymessage", "set", "remove", "limit", "config", "list"]],
  ["welcome", "Welcome & welcome DMs", ["welcome", "on", "off", "channel", "message", "test", "reset", "config", "welcomedm", "welcomedm on", "welcomedm off", "welcomedm message", "welcomedm test", "welcomedm reset", "welcomedm config"]],
  ["ticket", "Tickets", ["ticket", "panel", "add", "remove", "open", "close", "delete", "rename", "remind"]],
  ["voicetracker", "Voice tracker", ["voice", "add voice", "remove voice", "reset voice", "blacklist add", "blacklist remove", "blacklist list", "manager"]],
  ["autorole", "Auto roles", ["autorole", "set", "remove", "reset", "config"]],
  ["greet", "Greetings", ["greet", "set", "unset", "test", "autodel", "list"]],
  ["embed", "Embeds", ["embed", "create", "edit", "list", "show", "send", "delete", "variables"]],
  ["leaderboard", "Leaderboards", ["leaderboard", "messages", "dailymessages", "weeklymessages", "voice", "dailyvoice", "weeklyvoice", "invites", "liveleaderboard", "liveleaderboard setup", "liveleaderboard reset", "liveleaderboard config"]],
  ["invitetracker", "Invite tracker", ["invites", "invited", "inviteinfo", "inviter", "alternate", "alternate set", "alternate reset", "alternate config", "set", "set joinchannel", "set joinmessage", "set leavechannel", "set leavemessage", "unset", "unset joinchannel", "unset joinmessage", "unset leavechannel", "unset leavemessage", "add invite", "remove invite", "reset invite", "manager"]],
  ["giveaway", "Giveaways", ["gstart", "gend", "greroll", "gsetup", "gsetup thumbnail", "gsetup image", "gsetup color", "gsetup emoji", "gsetup reset", "gsetup view", "gedit", "gedit thumbnail", "gedit image", "gedit color", "gedit host", "gedit duration", "gedit prize", "gmanager", "gmanager set", "gmanager reset", "gmanager config", "gallow", "gban", "gban add", "gban remove", "gban list", "glist"]],
  ["jointocreate", "Join to create", ["jointocreate", "setup", "view", "interface", "category", "permissions", "reset", "permit"]],
  ["boostrole", "Booster roles", ["boostrole", "on", "off", "create", "rename", "color", "icon", "share", "unshare", "remove", "baserole", "list", "sharelimit", "filter", "message", "setchannel", "testmessage", "display", "config"]],
  ["utility", "Utility", ["afk", "avatar", "banner", "boostcount", "channelcount", "emojilist", "enlarge", "firstmsg", "serverbanner", "ignore", "ignore channel add", "ignore channel remove", "ignore channel list", "ignore channel reset", "ignore bypass add", "ignore bypass remove", "ignore bypass list", "ignore bypass reset", "imagelink", "vcrole", "membercount", "roleinfo", "servericon", "serverinfo", "steal", "translate", "userinfo", "vanityinfo", "mention", "help", "ping", "prefix", "premium", "profile", "report", "stats", "support", "uptime"]],
].map(([name, title, actions]) => ({ name, title, actions }));
